AtendimentoEsoterico/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MySql.Data.MySqlClient;
using AtendimentoEsoterico;
using System.Data;

namespace AtendimentoEsoterico.Controllers
{
    public class ChatController : Controller
    {
        BancoComandos bd = new BancoComandos();
        // GET: Chat
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Conversar(int id)
        {
            if (Request.Form.Count > 0)
            {
                string nome = Request.Form.Get("nome");
                string email = Request.Form.Get("email");
                string telefone = Request.Form.Get("telefone");
                string tempo = Request.Form.Get("tempo");
                string query = "insert into aspnet_atendimento(nomeCliente, emailCliente, telefoneCliente, tempoAtendimento, consultor_id) values (@nome, @email, @telefone, @tempo, @id)";
                MySqlParameter[] param = new MySqlParameter[]
                {
                new MySqlParameter("@nome", nome),
                new MySqlParameter("@email", email),
                new MySqlParameter("@telefone", telefone),
                new MySqlParameter("@tempo", tempo),
                new MySqlParameter("@id", id)
                };
                int linhasAfetadas = bd.Set(query, param);
                if (linhasAfetadas > 0)
                {
                    query = "select * FROM aspnet_atendimento inner join aspnet_consultor on id_consultor = consultor_id where nomeCliente = @nome and emailCliente = @email and telefoneCliente = @telefone and tempoAtendimento = @tempo and consultor_id = @id order by atendimento_id desc";
                    DataRow dr = bd.Get(query, param).Tables[0].Rows[0];
                    ViewBag.Dados = dr;
                    ViewBag.Nome = dr[7];
                    Session.Add("meuNome", dr[1]);
                    Session.Add("remetente", dr[0]);
                    Session.Add("destinatario", dr[5]);
                    return View();
                }
                else
                {
                    ViewBag.Error = "Erro ao inserir";
                    return View("FormCliente");
                }
            }
            else
            {
                string query = "select * FROM aspnet_atendimento inner join aspnet_consultor on id_consultor = consultor_id where consultor_id = " + id + " order by atendimento_id desc";
                DataRow dr = bd.Get(query, null).Tables[0].Rows[0];
                ViewBag.Dados = dr;
                ViewBag.Nome = dr[1];
                Session.Add("meuNome", dr[7]);
                Session.Add("remetente", dr[5]);
                Session.Add("destinatario", dr[0]);
                return View();
            }
        }
        public ActionResult FormCliente(int id)
        {
            ViewBag.Id = id;
            return View();
        }
        [HttpPost]
        public JsonResult salvaMensagem()
        {
            string json = "";
            try
            {
                string mensagem = Request.Form.Get("mensagem");
                string remetente = Request.Form.Get("remetente");
                string destinatario = Request.Form.Get("destinatario");
                string query = "insert into aspnet_chat (conteudo_mensagem, remetente, destinatario, lido) values (@mensagem, @remetente, @destinatario, @lido);";
                MySqlParameter[] mySqlParameter = new MySqlParameter[]
                {
                new MySqlParameter("@mensagem", mensagem),
                new MySqlParameter("@remetente", int.Parse(remetente)),
                new MySqlParameter("@destinatario", int.Parse(destinatario)),
                new MySqlParameter("@lido", 2)
                };
                int linhasAfetadas = bd.Set(query, mySqlParameter);
                if (linhasAfetadas > 0)
                {
                    json = "Enviada com sucesso";
                }
                else
                {
                    json = "Mensagem não enviada";
                }
            }
            catch(MySqlException ex)
            {
                json = ex.Message.ToString();
            }
            return Json(new { retorno = json });
        }

        public JsonResult buscaMensagem()
        {
            string remetente = Request.Form.Get("remetente");
            string destinatario = Request.Form.Get("destinatario");
            string query = "select * FROM aspnet_chat where remetente = @remetente and destinatario = @destinatario and lido = 2";
            MySqlParameter[] param = new MySqlParameter[]
            {
                new MySqlParameter("@remetente", int.Parse(remetente)),
                new MySqlParameter("@destinatario", int.Parse(destinatario))
            };
            DataTable dt = bd.Get(query, param).Tables[0];
            object[] mensagem = new object[dt.Rows.Count];
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                object[] conteudoMensagem = new object[3];
                conteudoMensagem[0] = dt.Rows[i][1].ToString();
                conteudoMensagem[1] = dt.Rows[i][3].ToString();
                conteudoMensagem[2] = dt.Rows[i][2].ToString();
                mensagem[i] = conteudoMensagem;
            }
            for(int i = 0; i < dt.Rows.Count; i++)
            {
                query = "update aspnet_chat set lido = 3 where id_mensagem = " + dt.Rows[i][0] + ";";
                bd.Set(query, null);
            }
            return Json(mensagem);
        }

        public bool buscaMensagemConsultor(string destinatario)
        {
            string query = "select * FROM aspnet_chat where destinatario = @destinatario and lido = 2";
            MySqlParameter[] param = new MySqlParameter[]
            {
                new MySqlParameter("@destinatario", int.Parse(destinatario))
            };
            int dt = bd.Get(query, param).Tables[0].Rows.Count;

            return (dt > 0);
        }
    }
}

AtendimentoEsoterico/Views/Chat/Conversar.cshtml
@{
    ViewBag.Title = "Conversar";
}
@{
    System.Data.DataRow dr = null;
    string nome = null;
    try { dr = ViewBag.Dados; } catch (Exception ex) { Console.Write(ex); }
    try { nome = ViewBag.Nome; } catch (Exception ex) { Console.Write(ex); }
}
@try
{
    <h2>Chat com @nome</h2>
}
catch (Exception ex)
{
    <small>@ex.Message</small>
}
<script type="text/javascript">
    var tempo = new Number();
    var vetor = { 2: 120, 5: 300, 30: 1800, 60: 3600 };
    valorGanhoString = "";
    var tempoCrescente = new Number();
    tempoCrescente = 0;
    var valorGanho = 0.00;
    tempo = vetor[@int.Parse(dr[4].ToString())]; // Tempo em segundos
    function pegarMensagem() {
            $.ajax({
                    url: "@Url.Action("buscaMensagem", "Chat")",
                    dataType: "json",
                    method: "post",
                    data: { remetente: @Session["destinatario"], destinatario: @Session["remetente"] },
                success: function (e) {
                    $.each(e, function (i, mensagem) {
                        var mensagemEnviada = "<div class='message-candidate center - block'>" +
                                                    "<div class='row' >" +
                                                        "<div class='col-xs-8 col-md-6'>" +
                                                            "<img src='http://imgc.allpostersimages.com/images/P-473-488-90/68/6896/2GOJ100Z/posters/despicable-me-2-minions-movie-poster.jpg' class='message-photo'>" +
                                                            "<h4 class='message-name'>@ViewBag.Nome</h4>" +
                                                        "</div>" +
                                                        "<div class='col-xs-4 col-md-6 text-right message-date'>Date here</div>" +
                                                    "</div>" +
                                                    "<div class='row message-text'>" +
                                                        mensagem[0] +
                                                    "</div>" +
                                                "</div >";
                        $("#conteudo").append(mensagemEnviada);    
                        });

                    },
                    error: function (e) {
                        console.log(e);
                    }
                });
    }
    function horaImprimivel(tempo) {
        var min = parseInt(tempo / 60); // Pega a parte inteira dos minutos
        var seg = tempo % 60; // Calcula os segundos restantes
        // Formata o número menor que dez, ex: 08, 07, ...
        if (min < 10) {
            min = "0" + min;
            min = min.substr(0, 2);
        }
        if (seg <= 9) {
            seg = "0" + seg;
        }
        return " " + min + ':' + seg;
    }
    function startCountdown() {
        if ((tempo - 1) >= 0) { // Se o tempo não for zerado

            // Cria a variável para formatar no estilo hora/cronômetro
            if (tempo <= 20) {
                $("#tempo").css("color", "Red");
                $("#tempo").css("font-size", "24px");
            }
            if(tempo%1 == 0) pegarMensagem();
            $("#tempo").html(horaImprimivel(tempo)); //JQuery pra setar o valor
            $("#tempoCrescente").html(horaImprimivel(tempoCrescente));
            valorGanhoString = "R$ " + parseFloat(Math.round(valorGanho * 100) / 100).toFixed(2);
            $("#valorGanho").html(valorGanhoString.replace(".", ",")); //JQuery pra setar o valor
            setTimeout('startCountdown()', 1000); // Define que a função será executada novamente em 1000ms = 1 segundo
            tempo--; // diminui o tempo
            tempoCrescente++; // diminui o tempo
            valorGanho += 0.03;
            //pegarMensagem();
        }
        else { // Quando o contador chegar a zero faz esta ação
            window.open("/", "_self");
        }
    }
    startCountdown();
</script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#mensagem").keypress(function (e) {
            if (e.keyCode == 13) {
                enviaMensagem();
            }
        });
        $("#envioMensagem").click(function () {
            enviaMensagem();
        });
        function enviaMensagem() {
            var mensagemEu = "<div class='message-hiring-manager center-block'>"+
                        "<div class='row'>" +
                            "<div class='col-xs-8 col-md-6'>" +
                                "<img src='@( (Session["consultor"] != null ) ? @dr[8] : "http://imgc.allpostersimages.com/images/P-473-488-90/68/6896/2GOJ100Z/posters/despicable-me-2-minions-movie-poster.jpg")' class='message-photo'>"+
                                "<h4 class='message-name'>@Session["meuNome"]</h4>" +
                            "</div>" +
                            "<div class='col-xs-4 col-md-6 text-right message-date'>Date here</div>" +
                        "</div>" +
                        "<div class='row message-text'>" +
                            $("#mensagem").val() +
                        "</div>" +
                "</div>";
            var mensagemEnviar = $("#mensagem").val();
            if ($("#mensagem").val() != "") {
                $("#mensagem").val("");
                $("#conteudo").append(mensagemEu);
                $.ajax({
                    url: "@Url.Action("salvaMensagem", "Chat")",
                    dataType: "json",
                    method: "post",
                    data: { mensagem: mensagemEnviar, remetente: @Session["remetente"], destinatario: @Session["destinatario"] },
                    success: function (e) {
                        console.log(e);
                    },
                    error: function (e) {
                        console.log(e);
                    }
                });
            }
        }
    });
</script>
<style>
    .message-candidate {
        background: rgba(234, 175, 175, 0.31);
        padding: 40px;
        max-width: 600px;
        margin-bottom: 10px;
    }

    .message-hiring-manager {
        background: rgba(173, 221, 232, 0.31);
        padding: 40px;
        max-width: 600px;
        margin-bottom: 10px;
    }

    .messaging {
        max-width: 600px;
        margin-top: 20px;
    }

    .message-text {
        margin-top: 10px;
    }

    .message-photo {
        width: 40px;
        height: 40px;
        border-radius: 50%;
        object-fit: cover;
        object-position: center center;
        display: inline-block;
    }

    .message-name {
        margin-left: 10px;
        display: inline-block;
    }
</style>
<center>
    <table>
        <tr>
            <td style="padding-right: 2px"><h4>Tempo Restante:</h4> </td><td><h4 id="tempo"></h4></td>
            <td style="padding-right: 2px; padding-left: 2px"><h4>Tempo Passado:</h4> </td><td><h4 id="tempoCrescente"></h4></td>
            <td style="padding-right: 2px; padding-left: 2px"><h4>Valor Ganho:</h4> </td><td><h4 id="valorGanho"></h4></td>
        </tr>
    </table>
</center>
<div class="container">
    <div id="conteudo">

    </div>
    <div class="messaging center-block">
        <div class="row">

            <div class="col-md-12">
                <div class="input-group">
                    <input type="text" id="mensagem" class="form-control">
                    <span class="input-group-btn">
                        <button id="envioMensagem" class="btn btn-primary" type="button">Enviar</button>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>

AtendimentoEsoterico/Views/Chat/FormCliente.cshtml
@{
    ViewBag.Title = "Formulario de Atendimento";
}

<h2>FormCliente</h2>
<div class="container">
    <form class="form-horizontal" method="post" action="@Url.Action("Conversar", "Chat", new RouteValueDictionary(new { id = ViewBag.Id }))">
        <div class="form-group">
            <label class="control-label col-lg-2">Nome:</label>
            <div class="col-lg-10">
                <input type="text" class="form-control" name="nome" value="" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2">Email:</label>
            <div class="col-lg-10">
                <input type="text" class="form-control" name="email" value="" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2">Telefone:</label>
            <div class="col-lg-10">
                <input type="tel" class="form-control" name="telefone" value="" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-2">Tempo de Atendimento</label>
            <div class="col-lg-10">
                <select name="tempo" class="form-control">
                    <option value="0">Selecione o tempo de atendimento...</option>
                    <option value="2">2 minutos</option>
                    <option value="5">5 minutos</option>
                    <option value="30">30 minutos</option>
                    <option value="60">1 hora</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-10">
                <button role="button" class="btn btn-success" type="submit">Iniciar Conversa</button>
            </div>
        </div>
    </form>
</div>